# Generated by Django 4.1.7 on 2023-03-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0004_remove_book_cover_remove_book_sample"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="book_covers/"),
        ),
        migrations.AddField(
            model_name="book",
            name="sample",
            field=models.FileField(blank=True, null=True, upload_to="book_samples/"),
        ),
    ]
